triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 2211

   - name: releaseTrigger
     type: trigger
     version:
       message: 'create a AArelease from staging cluster. triggered:1'
