jobs:
  - name: ecs-man
    type: manifest
    steps:
      - GET: ecs-nginx
      - GET: trigger-dv-man

  - name: ecs-upgrade-deploy
    type: ecsDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: ecs-man
      - GET: ecs-cluster
