triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 2

  - name: releaseTrigger
    type: trigger
    version:
      message: 'create release from staging cluster. triggered:1'
