jobs:
# 
# # jobs for pipelines from CI thru PROD environment
#
# ################################
#
# # generate manifest
  - name: dev-manifest-1
    type: manifest
    steps:
      - IN: docker-image
      - IN: docker-options
      - TASK: managed

# # TEST deployment to Triton
  - name: deploy-to-dev
    type: deploy
    steps:
      - IN: dev-manifest-1
      - IN: joyent-dev-sw1
      - TASK: managed
