jobs:
  - name: nginx-manifest-11
    type: manifest
    steps:
      - IN: serial-trigger
      - IN: nginx-image-prod11
      - IN: dv-image
      - IN: box-opts
      - IN: dv-opts

  - name: deploy-11
    type: deploy
    steps:
      - IN: nginx-manifest-11
      - IN: ddc-cluster
      - TASK: managed
        deployMethod: upgrade
