triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 90765511111000000
   #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
