jobs:
  - name: manifestjob1
    type: manifest
    steps:
      - IN: ssdocker
      - IN: plv2-dopts1
      - IN: trigger-dv-man
      
  - name: manifestjob2
    type: manifest
    steps:
      - IN: ssdocker2
      #- IN: plv2-dopts1
      - IN: trigger-dv-man


  # - name: jatin-2
  #   type: manifest
  #   steps:
  #     - GET: box-sn
  #     - GET: trigger-dv-man

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: jatin-1
  #     - GET: jatin-2
  #     - GET: ecs-cluster

  # - name: tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: box-man-1
  #     - GET: tri-cluster

  #- name: gkeDeploy
   # type: gkeDeploy
   # steps:
    #  - GET: jD-1
    #  - GET: gke-cluster
    #  - TASK: managed
    #    deployMethod: upgrade

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: ddc-cluster
      
  # - name: tri-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: manifestjob2
  #     - IN: tri-cluster
  #     # - TASK: managed
  #     #   deployMethod: upgrade
  
  - name: ecsDeploy
    type: deploy
    steps:
      - IN: manifestjob2
      - IN: myLB
        applyTo:
          - manifest: manifestjob2 # it can only apply to one manifest
            image: ssdocker2 # it can only apply to one image in the manifest
            port: 3030 # it can only reference one port in the image
                             # these rules are mostly just for ECS
      
  # - name: tri-deploy123
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     #- IN: manifestjob2
  #     - IN: tri-cluster
  #     # - TASK: managed
  #     #   deployMethod: upgrade
      
  # - name: gke-deploy
  #   type: deploy
  #   steps:
  #     - IN: manifestjob1
  #     - IN: scale
  #     - IN: gkecluster
  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: dcl-cluster
