triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 122098118800
   #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
