triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 28111134

   - name: releaseTrigger
     type: trigger
     version:
       message: 'create aS release from staging cluster. triggered:1'
