triggers:
   - name: sh-trigger
     type: triggerss
     version:
       counter: 10011123
   #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
