jobs:

  - name: nginx-manifest-2
    type: manifest
    steps:
      - IN: dv-image
      
  - name: release-one
    type: release
    steps:
      - IN: version-resource
      - IN: nginx-manifest-2
      - TASK: managed
        bump: major
      
  - name: nginx-manifest-11
    type: manifest
    steps:
      - IN: serial-trigger
      - IN: nginx-image-prod11
        pull: false
        versionName: invalid
        versionNumber: 0
      - IN: release-one
      - IN: box-opts
      - IN: dv-opts
      

  - name: deploy-11
    type: deploy
    steps:
      - IN: nginx-manifest-11
      - IN: ddc-cluster
      - TASK: managed
        deployMethod: upgrade
