triggers:
   - name: sh-trigger
     type: 123trigger
     version:
       counter: 10
   #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
