triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 22

   - name: releaseTrigger
     type: trigger
     version:
       message: 'createS a AArelease from staging cluster. triggered:1'
