triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 33221234111

   - name: releaseTrigger
     type: trigger
     version:
       message: 'cqqreate a AArelease from staging cluster. triggered:1'
