jobs:
  - name: box-man-1
    type: manifest
    steps:
      - GET: box-sn
      - GET: trigger-dv-man

  - name: box-man-2
    type: manifest
    steps:
      - GET: box-nginx
      - GET: trigger-dv-man

  - name: ecs-deploy
    type: ecsDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: box-man-1
      - GET: box-man-2
      - GET: ecs-cluster
