triggers:
   - name: sh-trigger
     type: trigger
     version:
       counter: 90098809098
   #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
   # - name: sh-trigger-1
   #   type: trigger
   #   #version:
   #   counter: 1012
   # #   type: trigger
   #   version:
   #     message: '2q22qreate a AArelease from staging cluster. triggered:1'
